# Generated by Django 4.2.4 on 2024-10-23 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facebook_id', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_page_id', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_token_expires_in', models.DateTimeField(blank=True, null=True)),
                ('youtube_id', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_token_expires_in', models.DateTimeField(blank=True, null=True)),
                ('google_business_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('google_business_token_expires_in', models.DateTimeField(blank=True, null=True)),
                ('instagram_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_id', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_token_expires_in', models.DateTimeField(blank=True, null=True)),
                ('linkedin_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_id', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_token_expires_in', models.DateTimeField(blank=True, null=True)),
                ('pinterest_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('pinterest_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pinterest_token_expires_in', models.DateTimeField(blank=True, null=True)),
                ('tiktok_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('tiktok_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tiktok_token_expires_in', models.DateTimeField(blank=True, null=True)),
                ('thread_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('thread_token_expires_in', models.DateTimeField(blank=True, null=True)),
                ('twitter_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_token_expires_in', models.DateTimeField(blank=True, null=True)),
                ('slack_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('slack_id', models.CharField(blank=True, max_length=255, null=True)),
                ('slack_token_expires_in', models.DateTimeField(blank=True, null=True)),
                ('discord_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('discord_id', models.CharField(blank=True, max_length=255, null=True)),
                ('discord_token_expires_in', models.DateTimeField(blank=True, null=True)),
                ('tumblr_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('tumblr_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tumblr_token_expires_in', models.DateTimeField(blank=True, null=True)),
                ('medium_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('medium_id', models.CharField(blank=True, max_length=255, null=True)),
                ('medium_token_expires_in', models.DateTimeField(blank=True, null=True)),
                ('telegram_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_token_expires_in', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_id', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_token_expires_in', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
