# Generated by Django 5.0.6 on 2024-11-26 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='Flutterwave', max_length=20)),
                ('plan_id', models.CharField(blank=True, help_text='Plan ID from the payment provider', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('payment_date', models.DateTimeField()),
                ('gateway', models.CharField(max_length=50)),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_duration', models.IntegerField()),
                ('plan_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('customer_id', models.CharField(max_length=250)),
                ('tx_ref', models.CharField(max_length=250)),
                ('expiration_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_6digits', models.CharField(max_length=6)),
                ('last_4digits', models.CharField(max_length=4)),
                ('issuer', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=2)),
                ('card_type', models.CharField(max_length=20)),
                ('expiry_date', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('payment_months', models.PositiveIntegerField(default=1)),
                ('tx_ref', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=250, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('is_trial', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionplan')),
            ],
        ),
    ]
