# Generated by Django 5.0.6 on 2024-11-12 00:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_6digits', models.CharField(max_length=6)),
                ('last_4digits', models.CharField(max_length=4)),
                ('issuer', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=2)),
                ('card_type', models.CharField(max_length=20)),
                ('expiry_date', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='subscription.subscription')),
            ],
        ),
    ]
