# Generated by Django 5.0.6 on 2024-11-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='customer_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
