# Generated by Django 4.2.4 on 2024-05-23 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "facebook_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("twitter_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "instagram_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "linkedin_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "pinterest_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "snapchat_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tiktok_id", models.CharField(blank=True, max_length=100, null=True)),
                ("youtube_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "whatsapp_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "telegram_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reddit_id", models.CharField(blank=True, max_length=100, null=True)),
                ("tumblr_id", models.CharField(blank=True, max_length=100, null=True)),
                ("skype_id", models.CharField(blank=True, max_length=100, null=True)),
                ("viber_id", models.CharField(blank=True, max_length=100, null=True)),
                ("discord_id", models.CharField(blank=True, max_length=100, null=True)),
                ("twitch_id", models.CharField(blank=True, max_length=100, null=True)),
                ("medium_id", models.CharField(blank=True, max_length=100, null=True)),
                ("signal_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
