# Generated by Django 5.0.6 on 2024-11-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_customuser_is_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(blank=True, default='web', max_length=50, null=True),
        ),
    ]
