# Generated by Django 4.2.4 on 2024-10-23 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_socialmediauser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaUser',
        ),
    ]
