# Generated by Django 5.0.6 on 2024-11-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_customuser_provider_alter_customuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
